# Generated by Django 4.0.1 on 2022-02-02 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=150)),
                ('brand', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
            ],
        ),
    ]
